blueprint:
  name: Message when timer has finished and restart timer
  description: Send a message when the timer has finished. Can be used e.g. for open window notification. Should add condition to monitor if state is still true.
  domain: automation
  input:
    timer_target:
      name: Timer to monitor
      description: The timer that should be monitored
      selector:
        entity:
          domain:
          - timer
    message:
      description: The message that shall be sent via telegram
      name: Climate Device
      selector:
        text:
          multiline: false
    additional_conditions:
      name: Additional conditions
      description: |
        Extra conditions you may want to add to this automation 
        (Example: Window still open?)
      default: []
      selector:
        condition:
    additional_action:
      name: Additional action
      description: |
        Extra actions you may want to add to this automation 
        (Example: Restart timer, so that the message is sent again)
      default: []
      selector:
        condition:    
  
mode: single
trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: !input timer_target
condition:
  - alias: User pick
    condition: !input additional_conditions
action:
  - service: notify.telegram_notify
    data:
      message: !input message
  !input additional_action

    
